#Service Definition
version : "3.3"
services:
  webserver:
    image: ubuntu
    port:
     - "80:80"
    network:
     - webnet

  redis:
    image: redis
    networks:
     - webnet
 
# Network Defintition
network:
  webnet:

# Data Volume Defination
volumes:
  data-volume:

# Container link
links:
  - logserver
  - logserver:log01

# port open (host:container)
ports:
  - "3000"
  - "8000:8000"
  - "127.0.0.1:8000:8000"

# expose (container)
expose:
  - "3000"
